const vehicles = [{
    id: 7,
    category: "mobil",
    brand: "BMW",
    name: "BMW M4",
    price: 2850000000,
    year: 2026,
    type: "Coupe",
    image: "assets/cars/BMW M4.png",
    gallery: ["assets/cars/BMW M4.png", "assets/cars/BMW M4 hitam.png", "assets/cars/BMW M4 abu.png"],
    description: "Coupe performa tinggi dengan karakter balap M, akselerasi agresif, dan kabin driver-focused.",
    engine: "3.0L TwinPower Turbo",
    power: "510 HP",
    torque: "650 Nm",
    transmission: "8 M Steptronic",
    color: "White, Yellow, Black",
    capacity: "4 Penumpang",
    fuel: "Bensin",
    promo: "Priority delivery untuk booking bulan ini.",
    dp: 570000000,
    installment: 34200000,
    featured: true,
    features: ["M xDrive", "Adaptive suspension", "Carbon roof", "M differential", "Launch control"]
  },
  {
    id: 8,
    category: "mobil",
    brand: "BMW",
    name: "BMW M3",
    price: 2650000000,
    year: 2026,
    type: "Sedan Sport",
    image: "assets/cars/BMW M3.png",
    gallery: ["assets/cars/BMW M3.png", "assets/cars/BMW M3 biru.png", "assets/cars/BMW M3 kuning.png"],
    description: "Sedan performa M yang menyatukan kenyamanan empat pintu dengan tenaga motorsport.",
    engine: "3.0L TwinPower Turbo",
    power: "510 HP",
    torque: "650 Nm",
    transmission: "8 AT",
    color: "Blue, White, Black, Red",
    capacity: "5 Penumpang",
    fuel: "Bensin",
    promo: "Program tukar tambah mobil premium.",
    dp: 530000000,
    installment: 31800000,
    featured: false,
    features: ["M sport brake", "Live cockpit", "Carbon bucket", "Driving assistant", "M mode"]
  },
  {
    id: 9,
    category: "mobil",
    brand: "Porsche",
    name: "Porsche 911",
    price: 3850000000,
    year: 2026,
    type: "Sports Car",
    image: "assets/cars/porsche.png",
    gallery: ["assets/cars/porsche.png", "assets/cars/Porsche 911 hitam.png", "assets/cars/Porsche 911 ijo.png"],
    description: "Sports car ikonik dengan handling tajam, mesin responsif, dan aura premium khas Porsche.",
    engine: "3.0L Twin Turbo",
    power: "450 HP",
    torque: "530 Nm",
    transmission: "PDK",
    color: "Blue, Guards Red, Black",
    capacity: "4 Penumpang",
    fuel: "Bensin",
    promo: "Booking fee refundable selama masa promo.",
    dp: 770000000,
    installment: 46200000,
    featured: true,
    features: ["Sport chrono", "PASM", "PDK", "Bose audio", "Sport exhaust"]
  },
  {
    id: 10,
    category: "mobil",
    brand: "Porsche",
    name: "Porsche Cayenne",
    price: 3250000000,
    year: 2026,
    type: "SUV Premium",
    image: "assets/cars/Porsche Cayenne.png",
    gallery: ["assets/cars/Porsche Cayenne.png", "assets/cars/Porsche Cayenne merah.png", "assets/cars/Porsche Cayenne hitam.png"],
    description: "SUV premium bertenaga besar dengan kenyamanan harian dan DNA sport Porsche.",
    engine: "3.0L V6 Turbo",
    power: "353 HP",
    torque: "500 Nm",
    transmission: "8 AT",
    color: "Black, White, Gray, Blue",
    capacity: "5 Penumpang",
    fuel: "Bensin",
    promo: "Paket detailing ceramic coating.",
    dp: 650000000,
    installment: 39000000,
    featured: false,
    features: ["Air suspension", "Matrix LED", "PCM display", "Panoramic roof", "BOSE surround"]
  },
  {
    id: 11,
    category: "mobil",
    brand: "Lamborghini",
    name: "Lamborghini Revuelto",
    price: 10850000000,
    year: 2026,
    type: "Supercar",
    image: "assets/cars/Lamborghini Revuelto.png",
    gallery: ["assets/cars/Lamborghini Revuelto merah.png", "assets/cars/Lamborghini Revuelto pink.png", "assets/cars/kuning.png"],
    description: "Supercar V12 hybrid dengan desain ekstrem, akselerasi eksplosif, dan status koleksi kelas dunia.",
    engine: "6.5L V12 Hybrid",
    power: "1015 HP",
    torque: "725 Nm",
    transmission: "8 DCT",
    color: "Rosso, Nero, Verde, Arancio",
    capacity: "2 Penumpang",
    fuel: "Hybrid Bensin",
    promo: "Private consultation dan unit allocation terbatas.",
    dp: 2170000000,
    installment: 130200000,
    featured: true,
    features: ["Carbon monocoque", "AWD", "Active aero", "Telemetry", "Lift system"]
  },
  {
    id: 12,
    category: "mobil",
    brand: "Mercedes",
    name: "Mercedes C-Class",
    price: 995000000,
    year: 2026,
    type: "Sedan Premium",
    image: "assets/cars/Mercedes C-Class.png",
    gallery: ["assets/cars/Mercedes C-Class.png", "assets/cars/Mercedes C-Class hitam.png", "assets/cars/Mercedes C-Class biru.png"],
    description: "Sedan premium dengan kabin elegan, teknologi MBUX, dan kenyamanan khas Mercedes-Benz.",
    engine: "1.5L Mild Hybrid",
    power: "204 HP",
    torque: "300 Nm",
    transmission: "9G-Tronic",
    color: "Obsidian Black, Polar White, Gray",
    capacity: "5 Penumpang",
    fuel: "Mild Hybrid",
    promo: "Service package hingga 5 tahun.",
    dp: 199000000,
    installment: 11940000,
    featured: false,
    features: ["MBUX", "Ambient light", "Burmester audio", "Active brake", "Digital light"]
  },
  {
    id: 13,
    category: "mobil",
    brand: "Mercedes",
    name: "Mercedes G-Class",
    price: 6200000000,
    year: 2026,
    type: "Luxury SUV",
    image: "assets/cars/Mercedes G-Class.png",
    gallery: ["assets/cars/Mercedes G-Class.png", "assets/cars/Mercedes G-Class kuning.png", "assets/cars/Mercedes G-Class abu.png"],
    description: "Ikon SUV mewah dengan kemampuan off-road legendaris dan aura premium yang kuat.",
    engine: "4.0L V8 Biturbo",
    power: "585 HP",
    torque: "850 Nm",
    transmission: "9 AT",
    color: "Black, White, Emerald Green",
    capacity: "5 Penumpang",
    fuel: "Bensin",
    promo: "Personalized delivery ceremony.",
    dp: 1240000000,
    installment: 74400000,
    featured: false,
    features: ["Diff lock", "AMG ride", "Nappa leather", "Widescreen cockpit", "Burmester 3D"]
  },
  {
    id: 14,
    category: "mobil",
    brand: "Audi",
    name: "Audi RS5",
    price: 2100000000,
    year: 2026,
    type: "Coupe Sport",
    image: "assets/cars/Audi RS5.png",
    gallery: ["assets/cars/Audi RS5 hijau.png", "assets/cars/Audi RS5 oren.png", "assets/cars/Audi RS5 biru.png"],
    description: "Coupe sport Quattro yang stabil, cepat, dan punya interior digital khas Audi.",
    engine: "2.9L V6 Twin Turbo",
    power: "450 HP",
    torque: "600 Nm",
    transmission: "8 Tiptronic",
    color: "Nardo Gray, Red, Black",
    capacity: "4 Penumpang",
    fuel: "Bensin",
    promo: "Free premium window film.",
    dp: 420000000,
    installment: 25200000,
    featured: false,
    features: ["Quattro AWD", "Virtual cockpit", "RS exhaust", "Matrix LED", "Bang & Olufsen"]
  },

  {
    id: 23,
    category: "motor",
    brand: "Yamaha",
    name: "Yamaha XMAX Tech Max",
    price: 67000000,
    year: 2026,
    type: "Premium Scooter",
    image: "assets/bikes/Yamaha XMAX Tech Max.png",
    gallery: ["assets/bikes/Yamaha XMAX Tech Max.png", "assets/bikes/Yamaha XMAX Tech Max hitam.png", "assets/bikes/Yamaha XMAX Tech Max biru.png"],
    description: "Premium scooter 250 cc dengan kenyamanan touring dan fitur modern.",
    engine: "250 cc Blue Core",
    power: "22.8 HP",
    torque: "24.3 Nm",
    transmission: "CVT",
    color: "Dark Petrol, Black, Silver",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Bonus box touring untuk unit tertentu.",
    dp: 13400000,
    installment: 804000,
    featured: true,
    features: ["TFT navigation", "ABS", "Traction control", "Electric windshield", "Large storage"]
  },
  {
    id: 24,
    category: "motor",
    brand: "Kawasaki",
    name: "Kawasaki Ninja ZX-25R",
    price: 250000000,
    year: 2026,
    type: "Sport",
    image: "assets/bikes/Kawasaki Ninja ZX-25R.png",
    gallery: ["assets/bikes/Kawasaki Ninja ZX-25R.png", "assets/bikes/Kawasaki Ninja ZX-25R merah.png", "assets/bikes/Kawasaki Ninja ZX-25R putih.png"],
    description: "Motor sport 250 cc empat silinder dengan suara khas, quick shifter, dan performa sirkuit.",
    engine: "249 cc 4-Cylinder",
    power: "51 HP",
    torque: "22.9 Nm",
    transmission: "6 Speed",
    color: "Lime Green, Metallic Red, Pearl White",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Program booking priority.",
    dp: 50000000,
    installment: 3000000,
    featured: true,
    features: ["Quick shifter", "KTRC", "Power mode", "Slipper clutch", "TFT display"]
  },
  {
    id: 25,
    category: "motor",
    brand: "Honda",
    name: "Honda CBR250RR",
    price: 78000000,
    year: 2026,
    type: "Sport",
    image: "assets/bikes/Honda CBR250RR.png",
    gallery: ["assets/bikes/Honda CBR250RR.png", "assets/bikes/Honda CBR250RR biru.png", "assets/bikes/Honda CBR250RR hitam.png"],
    description: "Motor sport fairing dengan throttle by wire, handling tajam, dan tampilan agresif.",
    engine: "250 cc 2-Cylinder",
    power: "42 HP",
    torque: "25 Nm",
    transmission: "6 Speed",
    color: "Red, Black, Tricolor",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Cicilan sport ringan.",
    dp: 15600000,
    installment: 936000,
    featured: false,
    features: ["Throttle by wire", "Riding mode", "Quick shifter", "ABS", "LED lighting"]
  },

  {
    id: 27,
    category: "motor",
    brand: "Harley Davidson",
    name: "Harley Street Bob",
    price: 5000000000,
    year: 2026,
    type: "Cruiser",
    image: "assets/bikes/Harley Street Bob.png",
    gallery: ["assets/bikes/Harley Street Bob.png", "assets/bikes/Harley Street Bob hitam.png", "assets/bikes/Harley Street Bob merah.png"],
    description: "Cruiser berkarakter kuat dengan mesin besar, gaya bobber, dan aura eksklusif.",
    engine: "Milwaukee-Eight 114",
    power: "94 HP",
    torque: "155 Nm",
    transmission: "6 Speed",
    color: "Vivid Black, Redline Red, Oren",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Private test ride by appointment.",
    dp: 1000000000,
    installment: 60000000,
    featured: true,
    features: ["LED forward lighting", "Mini ape handlebar", "Cast wheels", "USB port", "ABS"]
  },
  {
    id: 28,
    category: "motor",
    brand: "Yamaha",
    name: "Yamaha MT-25",
    price: 58000000,
    year: 2026,
    type: "Naked Sport",
    image: "assets/bikes/Yamaha MT-25.png",
    gallery: ["assets/bikes/Yamaha MT-25.png", "assets/bikes/Yamaha MT-25 putih.png", "assets/bikes/Yamaha MT-25 hitam.png"],
    description: "Naked sport 250 cc dengan riding position tegak, desain agresif, dan akselerasi responsif.",
    engine: "250 cc 2-Cylinder",
    power: "36 HP",
    torque: "23.6 Nm",
    transmission: "6 Speed",
    color: "Blue, Black, Cyan",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Paket servis gratis.",
    dp: 11600000,
    installment: 696000,
    featured: false,
    features: ["LED projector", "Slipper clutch", "USD fork", "Digital meter", "Big bike look"]
  },
  {
    id: 29,
    category: "motor",
    brand: "Yamaha",
    name: "Yamaha R25",
    price: 72000000,
    year: 2026,
    type: "Sport",
    image: "assets/bikes/Yamaha R25.png",
    gallery: ["assets/bikes/Yamaha R25.png", "assets/bikes/Yamaha R25 merah.png", "assets/bikes/Yamaha R25 putih.png"],
    description: "Sport 250 cc berfairing dengan DNA R-Series dan performa menyenangkan.",
    engine: "250 cc 2-Cylinder",
    power: "36 HP",
    torque: "23.6 Nm",
    transmission: "6 Speed",
    color: "Racing Blue, Black, Red",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Booking cepat untuk warna favorit.",
    dp: 14400000,
    installment: 864000,
    featured: false,
    features: ["Slipper clutch", "USD fork", "LED lights", "Aero fairing", "Sport meter"]
  },
  {
    id: 30,
    category: "motor",
    brand: "Honda",
    name: "Honda CB150R",
    price: 33000000,
    year: 2026,
    type: "Naked Sport",
    image: "assets/bikes/nmax.png",
    gallery: ["assets/bikes/nmax.png", "assets/bikes/vario.png", "assets/bikes/zx25r.png"],
    description: "Naked sport 150 cc yang ringan, agresif, dan cocok untuk harian maupun touring pendek.",
    engine: "150 cc DOHC",
    power: "16.9 HP",
    torque: "13.8 Nm",
    transmission: "6 Speed",
    color: "Black, Red, White",
    capacity: "2 Penumpang",
    fuel: "Bensin",
    promo: "Gratis helm full face.",
    dp: 6600000,
    installment: 396000,
    featured: false,
    features: ["USD fork", "LED lighting", "Digital panel", "Slipper clutch", "Wavy disc brake"]
  }
];

const promoBanners = [{
    image: "assets/banners/promo-biru.png",
    alt: "Promo Spesial KARNA"
  },
  {
    image: "assets/banners/promo-tahun-baru.png",
    alt: "Promo Tahun Baru KARNA"
  },
  {
    image: "assets/banners/promo-performa.png",
    alt: "Promo Performa KARNA"
  }
];